### ISSUE TITLE
[HELP] Zulfbungee reporting a SocketException on a Paper server

### ISSUE THREAD

**Issue by CerialPvP** [Zulfen/ZulfBungee#18]
I'm not sure if this is something on my end, or a bug on the plugin, but here we are.
When I start my paper & velocity servers (i have debug mode on), my velocity server does not report any errors, but the paper servers reports the following:
```
06.03 03:49:17 [Server] [INFO] [ZulfBungee] Error while creating socket: java.net.SocketException: Invalid argument
```
Velocity config:
```yml
# - Key Setup -



# This is the port that this server will bind to, which will it listen for incoming connections on.

port: 8077



# The IP that this server will bind to. Similar to the "client-host" in the Spigot config.

# This should usually be left as 0.0.0.0, or 127.0.0.1, but feel free to change this if you need to -

# (i.e. you are on shared hosting / Pterodactyl)

host: "127.0.0.1"



# - Options -



# This will toggle the display of detailed messages about what is going to the console.

# When filing a bug report / checking for issues, this is extremely useful to know what exactly went wrong!

debug: true



# Enables or disables global scripts.

global-scripts: true



# - Storage -



# What kind of database should be used to store network variables.

# Currently, supported databases: MySQL, H2



# If you have no clue what this does, just leave this as the default.

storage-type: "h2"



# Each option should be self-explanatory if you know what you are doing.



# If you are using H2, this will not apply - these two settings only apply to remote databases.

storage-host: "localhost"

storage-port: 3306



# !! Change these from the default to improve security !!

storage-username: "username"

storage-password: "password"



storage-database: "database"



# [MySQL Setup]



# If you get errors in console because of SSL, disable it here, but it's better to set up SSL on the MySQL server.

mysql-use-ssl: true

mysql-verify-certificate: true
```

Paper config (each server has a different port, I made sure to open them):
```yml
# - Key Setup -



# The port which you defined in your proxy config.

server-port: 8077



# The IP of your proxy.

server-host: "51.222.208.87"



# The port which this client (this Spigot server) will bind to, so it can listen for the proxy.

client-port: 8160



# The IP this client will bind to.

# This should usually be left as 0.0.0.0, or 127.0.0.1, but feel free to change this if you need to -

# (i.e. you are on shared hosting / Pterodactyl)

client-host: "127.0.0.1"



# If your proxy cannot find the name of your server from



# - Options -



# How many milliseconds it will wait for a connection.

# A timeout will be pronounced if the server does not respond in this time.

connection-timeout: 6000





# This will toggle the display of detailed messages about what is going to the console.

# When filing a bug report / checking for issues, this is extremely useful to know what exactly went wrong!

debug: true
```
It was on 0.0.0.0, and it gave a different error, if you want it ill send it here.
